# Copyright (c) 2016-present, Facebook, Inc. All rights reserved.
#
# You are hereby granted a non-exclusive, worldwide, royalty-free license to
# use, copy, modify, and distribute this software in source code or binary
# form for use in connection with the web services and APIs provided by
# Facebook.
#
# As with any software that integrates with the Facebook platform, your use of
# this software is subject to the Facebook Developer Principles and Policies
# [http://developers.facebook.com/policy/]. This copyright notice shall be
# included in all copies or substantial portions of the software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from django import forms
from widgets import SelectizeWidget, SelectizeMultiWidget


class CountrySelect(forms.CharField):
    """
    Basic country select component that makes use of the selectize widget.
    """
    DEFAULT_CHOICES = [
        ('', '- Choose a country -'),
        ('AD', 'Andorra (AD)'),
        ('AE', 'United Arab Emirates (AE)'),
        ('AF', 'Afghanistan (AF)'),
        ('AG', 'Antigua and Barbuda (AG)'),
        ('AI', 'Anguilla (AI)'),
        ('AL', 'Albania (AL)'),
        ('AM', 'Armenia (AM)'),
        ('AN', 'Netherlands (AN)'),
        ('AO', 'Angola (AO)'),
        ('AR', 'Argentina (AR)'),
        ('AT', 'Austria (AT)'),
        ('AU', 'Australia (AU)'),
        ('AW', 'Aruba (AW)'),
        ('AX', 'Aland Islands (AX)'),
        ('AZ', 'Azerbaijan (AZ)'),
        ('BA', 'Bosnia and Herzegovina (BA)'),
        ('BB', 'Barbados (BB)'),
        ('BD', 'Bangladesh (BD)'),
        ('BE', 'Belgium (BE)'),
        ('BF', 'Burkina (BF)'),
        ('BG', 'Bulgaria (BG)'),
        ('BH', 'Bahrain (BH)'),
        ('BJ', 'Benin (BJ)'),
        ('BM', 'BERMUDA (BM)'),
        ('BN', 'Brunei (BN)'),
        ('BO', 'Bolivia (BO)'),
        ('BR', 'Brazil (BR)'),
        ('BS', 'Bahamas (BS)'),
        ('BT', 'Bhutan (BT)'),
        ('BW', 'Botswana (BW)'),
        ('BY', 'Belarus (BY)'),
        ('BZ', 'Belize (BZ)'),
        ('CA', 'Canada (CA)'),
        ('CD', 'Congo Dem. (CD)'),
        ('CG', 'Congo (CG)'),
        ('CH', 'Switzerland (CH)'),
        ('CI', 'COTE D\'IVOIRE (CI)'),
        ('CL', 'Chile (CL)'),
        ('CM', 'Cameroon (CM)'),
        ('CN', 'China (CN)'),
        ('CO', 'Colombia (CO)'),
        ('CR', 'Costa Rica (CR)'),
        ('CU', 'Cuba (CU)'),
        ('CY', 'Cyprus (CY)'),
        ('CZ', 'Czech Republic (CZ)'),
        ('DE', 'Germany (DE)'),
        ('DJ', 'Djibouti (DJ)'),
        ('DK', 'Denmark (DK)'),
        ('DM', 'Dominica (DM)'),
        ('DO', 'Dominica (DO)'),
        ('DZ', 'Algeria (DZ)'),
        ('EC', 'Ecuador (EC)'),
        ('EE', 'Estonia (EE)'),
        ('EG', 'Egypt (EG)'),
        ('ES', 'Spain (ES)'),
        ('ET', 'Ethiopia (ET)'),
        ('FI', 'Finland (FI)'),
        ('FJ', 'Fiji (FJ)'),
        ('FO', 'FAROE ISLANDS (FO)'),
        ('FR', 'France (FR)'),
        ('GA', 'Gabon (GA)'),
        ('GB', 'United Kingdom (GB)'),
        ('GD', 'Grenada (GD)'),
        ('GE', 'Georgia (GE)'),
        ('GF', 'FRENCH GUIANA (GF)'),
        ('GG', 'GUERNSEY (GG)'),
        ('GH', 'Ghana (GH)'),
        ('GI', 'GIBRALTAR (GI)'),
        ('GL', 'GREENLAND (GL)'),
        ('GM', 'Gambia (GM)'),
        ('GP', 'GUADELOUPE (GP)'),
        ('GR', 'Greece (GR)'),
        ('GT', 'Guatemala (GT)'),
        ('GU', 'GUAM (GU)'),
        ('GY', 'Guyana (GY)'),
        ('HK', 'HONG KONG (HK)'),
        ('HN', 'Honduras (HN)'),
        ('HR', 'Croatia (HR)'),
        ('HT', 'Haiti (HT)'),
        ('HU', 'Hungary (HU)'),
        ('ID', 'Indonesia (ID)'),
        ('IE', 'Ireland (IE)'),
        ('IL', 'Israel (IL)'),
        ('IM', 'ISLE OF MAN (IM)'),
        ('IN', 'India (IN)'),
        ('IQ', 'Iraq (IQ)'),
        ('IR', 'Iran (IR)'),
        ('IS', 'Iceland (IS)'),
        ('IT', 'Italy (IT)'),
        ('JE', 'JERSEY (JE)'),
        ('JM', 'Jamaica (JM)'),
        ('JO', 'Jordan (JO)'),
        ('JP', 'Japan (JP)'),
        ('KE', 'Kenya (KE)'),
        ('KG', 'Kyrgyzstan (KG)'),
        ('KH', 'Cambodia (KH)'),
        ('KN', 'St. Kitts and Nevis (KN)'),
        ('KR', 'South Korea (KR)'),
        ('KW', 'Kuwait (KW)'),
        ('KY', 'CAYMAN ISLANDS (KY)'),
        ('KZ', 'Kazakhstan (KZ)'),
        ('LA', 'Laos (LA)'),
        ('LB', 'Lebanon (LB)'),
        ('LC', 'St. Lucia (LC)'),
        ('LI', 'Liechtenstein (LI)'),
        ('LK', 'Sri Lanka (LK)'),
        ('LS', 'Lesotho (LS)'),
        ('LT', 'Lithuania (LT)'),
        ('LU', 'Luxembourg (LU)'),
        ('LV', 'Latvia (LV)'),
        ('LY', 'Libya (LY)'),
        ('MA', 'Morocco (MA)'),
        ('MC', 'Monaco (MC)'),
        ('MD', 'Moldova (MD)'),
        ('ME', 'Montenegro (ME)'),
        ('MG', 'Madagascar (MG)'),
        ('MK', 'Macedonia (MK)'),
        ('ML', 'Mali (ML)'),
        ('MM', 'Myanmar (MM)'),
        ('MN', 'Mongolia (MN)'),
        ('MO', 'Macao (MO)'),
        ('MP', 'NORTHERN MARIANA ISLANDS (MP)'),
        ('MQ', 'MARTINIQUE (MQ)'),
        ('MR', 'Mauritania (MR)'),
        ('MT', 'Malta (MT)'),
        ('MU', 'Mauritius (MU)'),
        ('MV', 'Maldives (MV)'),
        ('MW', 'Malawi (MW)'),
        ('MX', 'Mexico (MX)'),
        ('MY', 'Malaysia (MY)'),
        ('MZ', 'Mozambique (MZ)'),
        ('NA', 'Namibia (NA)'),
        ('NC', 'NEW CALEDONIA (NC)'),
        ('NE', 'Niger (NE)'),
        ('NG', 'Nigeria (NG)'),
        ('NI', 'Nicaragua (NI)'),
        ('NL', 'Netherlands (NL)'),
        ('NO', 'Norway (NO)'),
        ('NP', 'Nepal (NP)'),
        ('NZ', 'New Zealand (NZ)'),
        ('OM', 'Oman (OM)'),
        ('PA', 'Panama (PA)'),
        ('PE', 'Peru (PE)'),
        ('PF', 'FRENCH POLYNESIA (PF)'),
        ('PG', 'Papua New Guinea (PG)'),
        ('PH', 'Philippines (PH)'),
        ('PK', 'Pakistan (PK)'),
        ('PL', 'Poland (PL)'),
        ('PR', 'PUERTO RICO (PR)'),
        ('PS', 'PALESTINIAN TERRITORY (PS)'),
        ('PT', 'Portugal (PT)'),
        ('PY', 'Paraguay (PY)'),
        ('QA', 'Qatar (QA)'),
        ('RO', 'Romania (RO)'),
        ('RS', 'Serbia (RS)'),
        ('RU', 'Russian (RU)'),
        ('RW', 'Rwanda (RW)'),
        ('SA', 'Saudi Arabia (SA)'),
        ('SC', 'Seychelles (SC)'),
        ('SD', 'Sudan (SD)'),
        ('SE', 'Sweden (SE)'),
        ('SG', 'Singapore (SG)'),
        ('SI', 'Slovenia (SI)'),
        ('SK', 'Slovakia (SK)'),
        ('SL', 'Sierra Leone (SL)'),
        ('SM', 'San Marino (SM)'),
        ('SN', 'Senegal (SN)'),
        ('SR', 'Suriname (SR)'),
        ('SV', 'El Salvador (SV)'),
        ('SY', 'Syria (SY)'),
        ('SZ', 'Swaziland (SZ)'),
        ('TC', 'TURKS AND CAICOS ISLANDS (TC)'),
        ('TG', 'Togo (TG)'),
        ('TH', 'Thailand (TH)'),
        ('TN', 'Tunisia (TN)'),
        ('TR', 'Turkey (TR)'),
        ('TT', 'Trinidad and Tobago (TT)'),
        ('TW', 'Taiwan (TW)'),
        ('TZ', 'Tanzania (TZ)'),
        ('UA', 'Ukraine (UA)'),
        ('UG', 'Uganda (UG)'),
        ('US', 'United States (US)'),
        ('UY', 'Uruguay (UY)'),
        ('UZ', 'Uzbekistan (UZ)'),
        ('VC', 'St. Vincent and the Grenadines (VC)'),
        ('VE', 'Venezuela (VE)'),
        ('VG', 'VIRGIN ISLANDS, BRITISH (VG)'),
        ('VI', 'VIRGIN ISLANDS, U.S. (VI)'),
        ('VN', 'Vietnam (VN)'),
        ('YE', 'Yemen (YE)'),
        ('YT', 'MAYOTTE (YT)'),
        ('ZA', 'South Africa (ZA)'),
        ('ZM', 'Zambia (ZM)'),
        ('ZW', 'Zimbabwe (ZW)'),
    ]

    def __init__(
        self,
        id='id_country_select',
        multiple=False,
        *args,
        **kwargs
    ):
        super(CountrySelect, self).__init__(*args, **kwargs)

        self.id = id

        args = {'attrs': {'id': self.id},
                'choices': self.DEFAULT_CHOICES
                }

        self.widget = SelectizeMultiWidget(**args) if multiple \
            else SelectizeWidget(**args)
